//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MifareOneTool.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MifareOneTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [0-9A-Fa-f]{32}.
        /// </summary>
        public static string _0_9A_Fa_f_32 {
            get {
                return ResourceManager.GetString("_0_9A_Fa_f_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à false.
        /// </summary>
        public static string _false {
            get {
                return ResourceManager.GetString("_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .mfd.
        /// </summary>
        public static string _mfd {
            get {
                return ResourceManager.GetString("_mfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ##NonceCollected##.
        /// </summary>
        public static string _Nonce收集完毕 {
            get {
                return ResourceManager.GetString("_Nonce收集完毕", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à +Sector: .
        /// </summary>
        public static string _Sector {
            get {
                return ResourceManager.GetString("_Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à true.
        /// </summary>
        public static string _true {
            get {
                return ResourceManager.GetString("_true", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  different blocks
        ///.
        /// </summary>
        public static string _个块不同 {
            get {
                return ResourceManager.GetString("_个块不同", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ##Saved-.
        /// </summary>
        public static string _已保存 {
            get {
                return ResourceManager.GetString("_已保存", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ##Automatically saved-.
        /// </summary>
        public static string _已自动保存 {
            get {
                return ResourceManager.GetString("_已自动保存", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #Sector .
        /// </summary>
        public static string _扇区 {
            get {
                return ResourceManager.GetString("_扇区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ##Wrong value in file##.
        /// </summary>
        public static string _文件中的值错误 {
            get {
                return ResourceManager.GetString("_文件中的值错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Has data.
        /// </summary>
        public static string _有数据 {
            get {
                return ResourceManager.GetString("_有数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  wrong.
        /// </summary>
        public static string _有错误 {
            get {
                return ResourceManager.GetString("_有错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ##Unsaved##.
        /// </summary>
        public static string _未保存 {
            get {
                return ResourceManager.GetString("_未保存", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ##The program has been forced to stop##.
        /// </summary>
        public static string _程序已被强制停止 {
            get {
                return ResourceManager.GetString("_程序已被强制停止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Empty sector.
        /// </summary>
        public static string _空扇区 {
            get {
                return ResourceManager.GetString("_空扇区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ##Cache file exception##.
        /// </summary>
        public static string _缓存文件异常 {
            get {
                return ResourceManager.GetString("_缓存文件异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ，Calculated BCC=.
        /// </summary>
        public static string _计算得到BCC {
            get {
                return ResourceManager.GetString("_计算得到BCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #Software version.
        /// </summary>
        public static string _软件版本 {
            get {
                return ResourceManager.GetString("_软件版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ##Running error##.
        /// </summary>
        public static string _运行出错 {
            get {
                return ResourceManager.GetString("_运行出错", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ##Running finished##.
        /// </summary>
        public static string _运行完毕 {
            get {
                return ResourceManager.GetString("_运行完毕", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AB One or two of the files are invalid。.
        /// </summary>
        public static string AB文件中一个或两个无效 {
            get {
                return ResourceManager.GetString("AB文件中一个或两个无效", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ACR122U support has been turned on..
        /// </summary>
        public static string ACR122U支持已经打开过 {
            get {
                return ResourceManager.GetString("ACR122U支持已经打开过", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à allow_autoscan = .
        /// </summary>
        public static string allow_autoscan {
            get {
                return ResourceManager.GetString("allow_autoscan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à allow_intrusive_scan = .
        /// </summary>
        public static string allow_intrusive_scan {
            get {
                return ResourceManager.GetString("allow_intrusive_scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à device.connstring = &quot;.
        /// </summary>
        public static string device_connstring {
            get {
                return ResourceManager.GetString("device_connstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à device.name = &quot;NFC-Device&quot;
        ///.
        /// </summary>
        public static string device_name_NFC_Device {
            get {
                return ResourceManager.GetString("device_name_NFC_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DUMP file|*.dump|MFD file|*.mfd.
        /// </summary>
        public static string DUMP文件_dump_MFD文件_mfd {
            get {
                return ResourceManager.GetString("DUMP文件_dump_MFD文件_mfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à InputError.
        /// </summary>
        public static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à KeyA/B/N.
        /// </summary>
        public static string KeyA_B_N {
            get {
                return ResourceManager.GetString("KeyA_B_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à libnfc.conf.
        /// </summary>
        public static string libnfc_conf {
            get {
                return ResourceManager.GetString("libnfc_conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MCT format|*.*.
        /// </summary>
        public static string MCT格式 {
            get {
                return ResourceManager.GetString("MCT格式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFD file|*.mfd;*.dump.
        /// </summary>
        public static string MFD文件_mfd_dump {
            get {
                return ResourceManager.GetString("MFD文件_mfd_dump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MFD file|*.mfd|DUMP file|*.dump.
        /// </summary>
        public static string MFD文件_mfd_DUMP文件_dump {
            get {
                return ResourceManager.GetString("MFD文件_mfd_DUMP文件_dump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MifareOne Tool.
        /// </summary>
        public static string MifareOne_Tool {
            get {
                return ResourceManager.GetString("MifareOne_Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MifareOne Tool - canceled.
        /// </summary>
        public static string MifareOne_Tool_已取消 {
            get {
                return ResourceManager.GetString("MifareOne_Tool_已取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MifareOne Tool - Terminated.
        /// </summary>
        public static string MifareOne_Tool_已终止 {
            get {
                return ResourceManager.GetString("MifareOne_Tool_已终止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MifareOne Tool - Running.
        /// </summary>
        public static string MifareOne_Tool_运行中 {
            get {
                return ResourceManager.GetString("MifareOne_Tool_运行中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MifareOne Tool - Running finished.
        /// </summary>
        public static string MifareOne_Tool_运行完毕 {
            get {
                return ResourceManager.GetString("MifareOne_Tool_运行完毕", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap outline_info_black_18pt_1x {
            get {
                object obj = ResourceManager.GetObject("outline_info_black_18pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 。.
        /// </summary>
        public static string res {
            get {
                return ResourceManager.GetString("res", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///.
        /// </summary>
        public static string res0 {
            get {
                return ResourceManager.GetString("res0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%.
        /// </summary>
        public static string res1 {
            get {
                return ResourceManager.GetString("res1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -- .
        /// </summary>
        public static string res2 {
            get {
                return ResourceManager.GetString("res2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ## .
        /// </summary>
        public static string res3 {
            get {
                return ResourceManager.GetString("res3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ：
        ///.
        /// </summary>
        public static string res4 {
            get {
                return ResourceManager.GetString("res4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_chevron_right_black_24dp {
            get {
                object obj = ResourceManager.GetObject("round_chevron_right_black_24dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_clear_black_24dp {
            get {
                object obj = ResourceManager.GetObject("round_clear_black_24dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_done_all_black_18pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_done_all_black_18pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_done_all_black_24dp {
            get {
                object obj = ResourceManager.GetObject("round_done_all_black_24dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_done_all_black_24pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_done_all_black_24pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_done_black_24pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_done_black_24pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_done_outline_black_24pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_done_outline_black_24pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_info_black_18pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_info_black_18pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_sync_black_18pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_sync_black_18pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_timer_black_18pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_timer_black_18pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_update_black_18pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_update_black_18pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_update_black_24pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_update_black_24pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Txt file|*.txt.
        /// </summary>
        public static string txt文件_txt {
            get {
                return ResourceManager.GetString("txt文件_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UID has been changed .
        /// </summary>
        public static string UID已改为 {
            get {
                return ResourceManager.GetString("UID已改为", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inappropriate 4-byte UID length.
        /// </summary>
        public static string 不恰当的4字节UID长度 {
            get {
                return ResourceManager.GetString("不恰当的4字节UID长度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use KeyA (yes) or KeyB (no)?.
        /// </summary>
        public static string 使用KeyA_是_或KeyB_否 {
            get {
                return ResourceManager.GetString("使用KeyA_是_或KeyB_否", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use KeyA (yes) or KeyB (no), or not (for new white cards) (cancel)? .
        /// </summary>
        public static string 使用KeyA_是_或KeyB_否_还是不使用_用于全新白卡_ {
            get {
                return ResourceManager.GetString("使用KeyA_是_或KeyB_否_还是不使用_用于全新白卡_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Russian.
        /// </summary>
        public static string 俄语 {
            get {
                return ResourceManager.GetString("俄语", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  found .
        /// </summary>
        public static string 共找到 {
            get {
                return ResourceManager.GetString("共找到", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Write error.
        /// </summary>
        public static string 写入出错 {
            get {
                return ResourceManager.GetString("写入出错", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  The size of the loaded S50 card file is abnormal. .
        /// </summary>
        public static string 加载的S50卡文件大小异常 {
            get {
                return ResourceManager.GetString("加载的S50卡文件大小异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  The loaded file does not exist. .
        /// </summary>
        public static string 加载的文件不存在 {
            get {
                return ResourceManager.GetString("加载的文件不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dangerous Operation Warning.
        /// </summary>
        public static string 危险操作警告 {
            get {
                return ResourceManager.GetString("危险操作警告", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Turning on ACR122U support at the same time may cause the operation speed to drop.
        ///Please confirm if you want to continue? .
        /// </summary>
        public static string 同时打开ACR122U支持可能会引起操作速度下降_请确认是否 {
            get {
                return ResourceManager.GetString("同时打开ACR122U支持可能会引起操作速度下降_请确认是否", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dictionary file|*.dic.
        /// </summary>
        public static string 字典文件_dic {
            get {
                return ResourceManager.GetString("字典文件_dic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key dictionary file|*.dic.
        /// </summary>
        public static string 密钥字典文件_dic {
            get {
                return ResourceManager.GetString("密钥字典文件_dic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  will automatically select the first device:.
        /// </summary>
        public static string 将自动选择首个设备 {
            get {
                return ResourceManager.GetString("将自动选择首个设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  There is an error in the file to be written. Please use the Hex tool in advanced mode to open the view. .
        /// </summary>
        public static string 将要写入的文件存在错误_请用高级模式中的Hex工具打开查看 {
            get {
                return ResourceManager.GetString("将要写入的文件存在错误_请用高级模式中的Hex工具打开查看", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saved as.
        /// </summary>
        public static string 已保存到 {
            get {
                return ResourceManager.GetString("已保存到", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  CUID empty card write patch enabled.
        /// </summary>
        public static string 已启用CUID空卡写入补丁 {
            get {
                return ResourceManager.GetString("已启用CUID空卡写入补丁", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  exported MCT file.
        /// </summary>
        public static string 已导出MCT文件 {
            get {
                return ResourceManager.GetString("已导出MCT文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exported key dictionary file.
        /// </summary>
        public static string 已导出密钥字典文件 {
            get {
                return ResourceManager.GetString("已导出密钥字典文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opened..
        /// </summary>
        public static string 已打开 {
            get {
                return ResourceManager.GetString("已打开", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Found! K=.
        /// </summary>
        public static string 已找到_K {
            get {
                return ResourceManager.GetString("已找到_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The NFC device has been specified :.
        /// </summary>
        public static string 已指定使用该NFC设备 {
            get {
                return ResourceManager.GetString("已指定使用该NFC设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Updated sector.
        /// </summary>
        public static string 已更新扇区 {
            get {
                return ResourceManager.GetString("已更新扇区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The card has been reset and created..
        /// </summary>
        public static string 已重置并新建卡 {
            get {
                return ResourceManager.GetString("已重置并新建卡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start executing CUID/FUID card writing....
        /// </summary>
        public static string 开始执行CUID_FUID卡片写入 {
            get {
                return ResourceManager.GetString("开始执行CUID_FUID卡片写入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  starts performing HardNested to collect data....
        /// </summary>
        public static string 开始执行HardNested收集数据 {
            get {
                return ResourceManager.GetString("开始执行HardNested收集数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  starts the HardNested decryption hardening card....
        /// </summary>
        public static string 开始执行HardNested解密强化卡 {
            get {
                return ResourceManager.GetString("开始执行HardNested解密强化卡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start performing MFOC decryption....
        /// </summary>
        public static string 开始执行MFOC解密 {
            get {
                return ResourceManager.GetString("开始执行MFOC解密", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  starts executing UFUID card lock....
        /// </summary>
        public static string 开始执行UFUID卡片锁定 {
            get {
                return ResourceManager.GetString("开始执行UFUID卡片锁定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  starts executing UID card full screen....
        /// </summary>
        public static string 开始执行UID卡片全格 {
            get {
                return ResourceManager.GetString("开始执行UID卡片全格", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  starts executing UID card writing....
        /// </summary>
        public static string 开始执行UID卡片写入 {
            get {
                return ResourceManager.GetString("开始执行UID卡片写入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  starts executing the UID card setting card number....
        /// </summary>
        public static string 开始执行UID卡片设定卡号 {
            get {
                return ResourceManager.GetString("开始执行UID卡片设定卡号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  starts UID card reading....
        /// </summary>
        public static string 开始执行UID卡片读取 {
            get {
                return ResourceManager.GetString("开始执行UID卡片读取", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start performing full encryption card blasting…….
        /// </summary>
        public static string 开始执行全加密卡片爆破 {
            get {
                return ResourceManager.GetString("开始执行全加密卡片爆破", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start writing M1 cards…….
        /// </summary>
        public static string 开始执行写入M1卡片 {
            get {
                return ResourceManager.GetString("开始执行写入M1卡片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start performing dictionary mode MFOC decryption…….
        /// </summary>
        public static string 开始执行字典模式MFOC解密 {
            get {
                return ResourceManager.GetString("开始执行字典模式MFOC解密", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start scanning cards…….
        /// </summary>
        public static string 开始执行扫描卡片 {
            get {
                return ResourceManager.GetString("开始执行扫描卡片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start executing the formatted M1 card…….
        /// </summary>
        public static string 开始执行格式化M1卡片 {
            get {
                return ResourceManager.GetString("开始执行格式化M1卡片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start performing check card encryption…….
        /// </summary>
        public static string 开始执行检测卡片加密 {
            get {
                return ResourceManager.GetString("开始执行检测卡片加密", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Starting device test…….
        /// </summary>
        public static string 开始执行检测设备 {
            get {
                return ResourceManager.GetString("开始执行检测设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à reading the card…….
        /// </summary>
        public static string 开始执行读取卡片 {
            get {
                return ResourceManager.GetString("开始执行读取卡片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à reset UID card number…….
        /// </summary>
        public static string 开始执行重置UID卡片卡号 {
            get {
                return ResourceManager.GetString("开始执行重置UID卡片卡号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The current sector data is still in error and cannot be modified..
        /// </summary>
        public static string 当前扇区数据仍有错误_不能执行修改 {
            get {
                return ResourceManager.GetString("当前扇区数据仍有错误_不能执行修改", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Currently selected sector:? ?.
        /// </summary>
        public static string 当前选定扇区 {
            get {
                return ResourceManager.GetString("当前选定扇区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Currently selected sector:.
        /// </summary>
        public static string 当前选定扇区0 {
            get {
                return ResourceManager.GetString("当前选定扇区0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can upload to the cloud computing service node for calculation。.
        /// </summary>
        public static string 您可以上传到云计算服务节点进行计算 {
            get {
                return ResourceManager.GetString("您可以上传到云计算服务节点进行计算", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have already run MifareOne Tool, and opening multiple programs may cause conflicts and unpredictable errors.
        ///Are you sure you want to continue?.
        /// </summary>
        public static string 您已经运行了MifareOne_Tool_打开多个本程序可能 {
            get {
                return ResourceManager.GetString("您已经运行了MifareOne_Tool_打开多个本程序可能", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are trying to run repeatedly.
        /// </summary>
        public static string 您正在试图重复运行 {
            get {
                return ResourceManager.GetString("您正在试图重复运行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  You have not given the card data file that caused 0 damage to the last write card as the key source when writing the card.
        ///The operation is terminated. .
        /// </summary>
        public static string 您没有给定最后一次写卡导致0块损坏的卡数据文件来作为写卡时的 {
            get {
                return ResourceManager.GetString("您没有给定最后一次写卡导致0块损坏的卡数据文件来作为写卡时的", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sector.
        /// </summary>
        public static string 扇区 {
            get {
                return ResourceManager.GetString("扇区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sector .
        /// </summary>
        public static string 扇区0 {
            get {
                return ResourceManager.GetString("扇区0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à opened.
        /// </summary>
        public static string 打开了 {
            get {
                return ResourceManager.GetString("打开了", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open error.
        /// </summary>
        public static string 打开出错 {
            get {
                return ResourceManager.GetString("打开出错", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prompt message.
        /// </summary>
        public static string 提示信息 {
            get {
                return ResourceManager.GetString("提示信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file does not contain 64 blocks of data and may be incomplete or incompatible..
        /// </summary>
        public static string 文件内不是含有64个块数据_可能不完整或不兼容 {
            get {
                return ResourceManager.GetString("文件内不是含有64个块数据_可能不完整或不兼容", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No key.
        /// </summary>
        public static string 无密钥 {
            get {
                return ResourceManager.GetString("无密钥", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  could not find the MFF08 program file.
        ///The operation is terminated. .
        /// </summary>
        public static string 无法找到MFF08程序文件_操作终止 {
            get {
                return ResourceManager.GetString("无法找到MFF08程序文件_操作终止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display sector.
        /// </summary>
        public static string 显示扇区 {
            get {
                return ResourceManager.GetString("显示扇区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  has a task running and cannot be executed. .
        /// </summary>
        public static string 有任务运行中_不可执行 {
            get {
                return ResourceManager.GetString("有任务运行中_不可执行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à unknown.
        /// </summary>
        public static string 未知 {
            get {
                return ResourceManager.GetString("未知", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A valid key.mfd was not selected..
        /// </summary>
        public static string 未选择有效key_mfd {
            get {
                return ResourceManager.GetString("未选择有效key_mfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local version .
        /// </summary>
        public static string 本地版本 {
            get {
                return ResourceManager.GetString("本地版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à standard.
        /// </summary>
        public static string 标准 {
            get {
                return ResourceManager.GetString("标准", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Using Smart KeyABN....
        /// </summary>
        public static string 正在使用智能KeyABN {
            get {
                return ResourceManager.GetString("正在使用智能KeyABN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opening ACR122U support....
        /// </summary>
        public static string 正在打开ACR122U支持 {
            get {
                return ResourceManager.GetString("正在打开ACR122U支持", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retrieving the existence of key.mfd....
        /// </summary>
        public static string 正在检索是否存在key_mfd {
            get {
                return ResourceManager.GetString("正在检索是否存在key_mfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  did not find any valid NFC devices. .
        /// </summary>
        public static string 没有发现任何有效的NFC设备 {
            get {
                return ResourceManager.GetString("没有发现任何有效的NFC设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à second.
        /// </summary>
        public static string 秒 {
            get {
                return ResourceManager.GetString("秒", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à idle.
        /// </summary>
        public static string 空闲 {
            get {
                return ResourceManager.GetString("空闲", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terminal content has been saved to the m1t.log file.
        /// </summary>
        public static string 终端内容已保存至m1t_log文件 {
            get {
                return ResourceManager.GetString("终端内容已保存至m1t_log文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Device serial port:.
        /// </summary>
        public static string 设备串口 {
            get {
                return ResourceManager.GetString("设备串口", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Busy device.
        /// </summary>
        public static string 设备忙 {
            get {
                return ResourceManager.GetString("设备忙", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  is set incorrectly, please modify it. .
        /// </summary>
        public static string 设置错误_请修改 {
            get {
                return ResourceManager.GetString("设置错误_请修改", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The following devices were identified:.
        /// </summary>
        public static string 识别了以下设备 {
            get {
                return ResourceManager.GetString("识别了以下设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  The UID check value of this sector is incorrect and has been automatically corrected for you.
        ///.
        /// </summary>
        public static string 该扇区UID校验值错误_已经自动为您更正 {
            get {
                return ResourceManager.GetString("该扇区UID校验值错误_已经自动为您更正", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  The UID check value of this sector is incorrect and has been automatically corrected.
        ///.
        /// </summary>
        public static string 该扇区UID校验值错误_已自动更正 {
            get {
                return ResourceManager.GetString("该扇区UID校验值错误_已自动更正", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  The UID check value of this sector is incorrect. Please click to open sector 0 to correct it automatically.
        ///.
        /// </summary>
        public static string 该扇区UID校验值错误_请点击打开扇区0来自动更正 {
            get {
                return ResourceManager.GetString("该扇区UID校验值错误_请点击打开扇区0来自动更正", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  The sector is all fine.
        ///.
        /// </summary>
        public static string 该扇区一切正常 {
            get {
                return ResourceManager.GetString("该扇区一切正常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  The sector access control bit is corrupted, writing will damage the card and has been reset.
        ///.
        /// </summary>
        public static string 该扇区访问控制位损坏_写入将会损坏卡片_已重新设置 {
            get {
                return ResourceManager.GetString("该扇区访问控制位损坏_写入将会损坏卡片_已重新设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  The sector access control bit is corrupted. Writing will damage the card. Please reset it.
        ///.
        /// </summary>
        public static string 该扇区访问控制位损坏_写入将会损坏卡片_请重新设置 {
            get {
                return ResourceManager.GetString("该扇区访问控制位损坏_写入将会损坏卡片_请重新设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  The sector access control bit is invalid. Writing will damage the card and has been reset.
        ///.
        /// </summary>
        public static string 该扇区访问控制位无效_写入将会损坏卡片_已重新设置 {
            get {
                return ResourceManager.GetString("该扇区访问控制位无效_写入将会损坏卡片_已重新设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  The sector access control bit is invalid. Writing will damage the card. Please reset it.
        ///.
        /// </summary>
        public static string 该扇区访问控制位无效_写入将会损坏卡片_请重新设置 {
            get {
                return ResourceManager.GetString("该扇区访问控制位无效_写入将会损坏卡片_请重新设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  This will erase all data in the UID card! ! !
        ///Cannot be restored after emptying! Please confirm if you want to continue? .
        /// </summary>
        public static string 该操作将会清空UID卡内全部数据_清空后不可恢复_请确认是否 {
            get {
                return ResourceManager.GetString("该操作将会清空UID卡内全部数据_清空后不可恢复_请确认是否", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  This will lock the UFUID card! ! !
        ///Unable to recover after locking! Unable to change 0 blocks again! Please confirm if you want to continue? .
        /// </summary>
        public static string 该操作将会锁死UFUID卡片_锁死后不可恢复_无法再次更改0 {
            get {
                return ResourceManager.GetString("该操作将会锁死UFUID卡片_锁死后不可恢复_无法再次更改0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  The file is all fine. .
        /// </summary>
        public static string 该文件一切正常 {
            get {
                return ResourceManager.GetString("该文件一切正常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file has the following error:
        ///.
        /// </summary>
        public static string 该文件存在以下错误 {
            get {
                return ResourceManager.GetString("该文件存在以下错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Please check if the wiring is correct/whether the drive is properly installed/device power is turned on (for models with power switch). .
        /// </summary>
        public static string 请检查接线是否正确_驱动是否正常安装_设备电源是否已经打开_ {
            get {
                return ResourceManager.GetString("请检查接线是否正确_驱动是否正常安装_设备电源是否已经打开_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter the UID number.
        /// </summary>
        public static string 请输入UID号 {
            get {
                return ResourceManager.GetString("请输入UID号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a known Key.
        /// </summary>
        public static string 请输入已知Key {
            get {
                return ResourceManager.GetString("请输入已知Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Please enter a known Key, separated by a comma. .
        /// </summary>
        public static string 请输入已知的Key_以英文半角逗号分隔 {
            get {
                return ResourceManager.GetString("请输入已知的Key_以英文半角逗号分隔", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Please enter the UID card number to be written, a total of 8 hexadecimal numbers, such as E44A3BF1. .
        /// </summary>
        public static string 请输入需要写入的UID卡号_共8位十六进制数_如E44A3B {
            get {
                return ResourceManager.GetString("请输入需要写入的UID卡号_共8位十六进制数_如E44A3B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Please enter the UID card number to be changed, a total of 8 hexadecimal numbers, such as E44A3BF1. .
        /// </summary>
        public static string 请输入需要更改的UID卡号_共8位十六进制数_如E44A3B {
            get {
                return ResourceManager.GetString("请输入需要更改的UID卡号_共8位十六进制数_如E44A3B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select the MCT.txt file to save the location and file name.
        /// </summary>
        public static string 请选择MCT_txt文件保存位置及文件名 {
            get {
                return ResourceManager.GetString("请选择MCT_txt文件保存位置及文件名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select the location and file name of the MFD file.
        /// </summary>
        public static string 请选择MFD文件保存位置及文件名 {
            get {
                return ResourceManager.GetString("请选择MFD文件保存位置及文件名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Please select an MFD file containing the target card key (usually the MFD file of the card that has been cracked).
        /// </summary>
        public static string 请选择一个包含目标卡密钥的MFD文件_通常是已经破解出的该卡 {
            get {
                return ResourceManager.GetString("请选择一个包含目标卡密钥的MFD文件_通常是已经破解出的该卡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select the key dictionary file save location and file name.
        /// </summary>
        public static string 请选择密钥字典文件保存位置及文件名 {
            get {
                return ResourceManager.GetString("请选择密钥字典文件保存位置及文件名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Please select the card data file that caused the 0 block damage after the last write of the card.
        /// </summary>
        public static string 请选择最后一次写卡导致0块损坏的卡数据文件 {
            get {
                return ResourceManager.GetString("请选择最后一次写卡导致0块损坏的卡数据文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select the MFD file to be written.
        /// </summary>
        public static string 请选择需要写入的MFD文件 {
            get {
                return ResourceManager.GetString("请选择需要写入的MFD文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select the MCT format file to be opened.
        /// </summary>
        public static string 请选择需要打开的MCT格式文件 {
            get {
                return ResourceManager.GetString("请选择需要打开的MCT格式文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select the MFD file you want to open.
        /// </summary>
        public static string 请选择需要打开的MFD文件 {
            get {
                return ResourceManager.GetString("请选择需要打开的MFD文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Please select the MFD file you want to open (compare A).
        /// </summary>
        public static string 请选择需要打开的MFD文件_比较A {
            get {
                return ResourceManager.GetString("请选择需要打开的MFD文件_比较A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Please select the MFD file you want to open (compare B).
        /// </summary>
        public static string 请选择需要打开的MFD文件_比较B {
            get {
                return ResourceManager.GetString("请选择需要打开的MFD文件_比较B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select the key dictionary file you want to open.
        /// </summary>
        public static string 请选择需要打开的密钥字典文件 {
            get {
                return ResourceManager.GetString("请选择需要打开的密钥字典文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  The UID number entered is not legal.
        /// </summary>
        public static string 输入的UID号不合法 {
            get {
                return ResourceManager.GetString("输入的UID号不合法", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Running.
        /// </summary>
        public static string 运行中 {
            get {
                return ResourceManager.GetString("运行中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run time:.
        /// </summary>
        public static string 运行时间 {
            get {
                return ResourceManager.GetString("运行时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select key.mfd.
        /// </summary>
        public static string 选择key_mfd {
            get {
                return ResourceManager.GetString("选择key_mfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à error.
        /// </summary>
        public static string 错误 {
            get {
                return ResourceManager.GetString("错误", resourceCulture);
            }
        }
    }
}
